name: frontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  google_sign_in: ^6.2.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1

  url_launcher: ^6.1.10
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.2

  flutter_map: ^7.0.2
  geocode: ^1.0.3
  latlong2: ^0.9.1
  carousel_slider: ^5.0.0
  number_paginator: ^0.4.1
  dynamic_height_grid_view: ^0.0.4
  image_picker: ^1.1.2
  mockito: ^5.4.4
  build_runner: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/opp.jpg
