name: Unit Tests

on:
  push:
    branches:
      - main
      - dev   
  pull_request:
    branches:
      - main
      - dev   

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'
      - name: Restore Dependencies
        run: dotnet restore BackEnd/BackEnd.Test/BackEnd.Test.csproj
      - name: Run Unit Tests
        run: dotnet test BackEnd/BackEnd.Test/BackEnd.Test.csproj --filter Category=UnitTest
